-- V20260704_001_tks_canonical_webphotocopyhub.sql
-- Canonical PostgreSQL schema for WebPhotocopyHub following TKS table, view,
-- tracking, and routine conventions. Object names are lower-case PostgreSQL
-- identifiers while retaining TKS prefixes.

BEGIN;

SET LOCAL search_path = public;

CREATE TABLE IF NOT EXISTS tbl_sys_database_version
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patch_id varchar(80) NOT NULL,
    description varchar(500) NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_by varchar(100) NOT NULL DEFAULT CURRENT_USER,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT uq_tbl_sys_database_version_patch UNIQUE (patch_id)
);

CREATE OR REPLACE FUNCTION fn_tks_set_tracking_columns()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.deleted := COALESCE(NEW.deleted, 0);

    IF TG_OP = 'INSERT' THEN
        NEW.created := COALESCE(NEW.created, CURRENT_TIMESTAMP);
        NEW.created_by := COALESCE(NEW.created_by, CURRENT_USER);
        NEW.created_by_function := COALESCE(NEW.created_by_function, TG_NAME);
    ELSE
        NEW.created := OLD.created;
        NEW.created_by := OLD.created_by;
        NEW.created_by_function := OLD.created_by_function;
    END IF;

    NEW.last_updated := CURRENT_TIMESTAMP;
    NEW.last_updated_by := COALESCE(NEW.last_updated_by, CURRENT_USER);
    NEW.last_updated_by_function := COALESCE(NEW.last_updated_by_function, TG_NAME);

    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS tbl_dm_chi_nhanh
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_chi_nhanh varchar(50) NOT NULL,
    slug varchar(80) NOT NULL,
    ten_chi_nhanh varchar(200) NOT NULL,
    dia_chi varchar(500),
    dien_thoai varchar(50),
    email varchar(200),
    gio_mo_cua varchar(200),
    mo_ta_ngan varchar(1000),
    ghi_chu_khach_hang varchar(1000),
    dich_vu_pho_bien_text varchar(2000),
    tuy_chon_nhanh_text varchar(2000),
    is_hoat_dong integer NOT NULL DEFAULT 1,
    is_nhan_don integer NOT NULL DEFAULT 1,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_chi_nhanh_ma
    ON tbl_dm_chi_nhanh (lower(ma_chi_nhanh))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_chi_nhanh_slug
    ON tbl_dm_chi_nhanh (lower(slug))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_chi_nhanh_legacy_uuid
    ON tbl_dm_chi_nhanh (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_sys_thanh_vien
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_dang_nhap varchar(256) NOT NULL,
    email varchar(256),
    ho_ten varchar(200) NOT NULL,
    dia_chi varchar(500),
    dien_thoai varchar(50),
    current_balance_legacy numeric(18,2) NOT NULL DEFAULT 0,
    is_hoat_dong integer NOT NULL DEFAULT 1,
    identity_user_id varchar(191),
    legacy_id varchar(191),
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_thanh_vien_ma
    ON tbl_sys_thanh_vien (lower(ma_dang_nhap))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_thanh_vien_identity
    ON tbl_sys_thanh_vien (identity_user_id)
    WHERE identity_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_sys_nhom_thanh_vien
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_nhom varchar(100) NOT NULL,
    ten_nhom varchar(150) NOT NULL,
    mo_ta varchar(500),
    is_system_role integer NOT NULL DEFAULT 0,
    is_hoat_dong integer NOT NULL DEFAULT 1,
    identity_role_id varchar(191),
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_nhom_thanh_vien_ma
    ON tbl_sys_nhom_thanh_vien (lower(ma_nhom))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_nhom_thanh_vien_identity
    ON tbl_sys_nhom_thanh_vien (identity_role_id)
    WHERE identity_role_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_sys_nhom_thanh_vien_user
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhom_thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_nhom_thanh_vien(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_nhom_thanh_vien_user
    ON tbl_sys_nhom_thanh_vien_user (nhom_thanh_vien_id, thanh_vien_id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_sys_chuc_nang
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint REFERENCES tbl_sys_chuc_nang(auto_id) ON DELETE RESTRICT,
    ma_chuc_nang varchar(100) NOT NULL,
    ten_chuc_nang varchar(200) NOT NULL,
    mo_ta varchar(500),
    area varchar(50),
    controller varchar(100),
    action varchar(100),
    icon_key varchar(50),
    ma_tinh_nang_chi_nhanh varchar(100),
    sort_order integer NOT NULL DEFAULT 0,
    is_chon_chi_nhanh integer NOT NULL DEFAULT 0,
    is_menu_item integer NOT NULL DEFAULT 1,
    is_hoat_dong integer NOT NULL DEFAULT 1,
    is_system_function integer NOT NULL DEFAULT 0,
    supports_view integer NOT NULL DEFAULT 1,
    supports_create integer NOT NULL DEFAULT 0,
    supports_edit integer NOT NULL DEFAULT 0,
    supports_delete integer NOT NULL DEFAULT 0,
    supports_export integer NOT NULL DEFAULT 0,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_chuc_nang_ma
    ON tbl_sys_chuc_nang (lower(ma_chuc_nang))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_chuc_nang_legacy_uuid
    ON tbl_sys_chuc_nang (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_sys_phan_quyen_chuc_nang
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nhom_thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_nhom_thanh_vien(auto_id) ON DELETE RESTRICT,
    chuc_nang_id bigint NOT NULL REFERENCES tbl_sys_chuc_nang(auto_id) ON DELETE RESTRICT,
    can_view integer NOT NULL DEFAULT 0,
    can_create integer NOT NULL DEFAULT 0,
    can_edit integer NOT NULL DEFAULT 0,
    can_delete integer NOT NULL DEFAULT 0,
    can_export integer NOT NULL DEFAULT 0,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_phan_quyen_chuc_nang
    ON tbl_sys_phan_quyen_chuc_nang (nhom_thanh_vien_id, chuc_nang_id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_sys_chi_nhanh_tinh_nang
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    ma_tinh_nang varchar(100) NOT NULL,
    ten_tinh_nang varchar(200),
    mo_ta varchar(500),
    is_enabled integer NOT NULL DEFAULT 1,
    updated_by_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_chi_nhanh_tinh_nang
    ON tbl_sys_chi_nhanh_tinh_nang (chi_nhanh_id, lower(ma_tinh_nang))
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_sys_vai_tro_chi_nhanh
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    ten_vai_tro varchar(100) NOT NULL,
    mo_ta varchar(500),
    is_system_role integer NOT NULL DEFAULT 0,
    is_hoat_dong integer NOT NULL DEFAULT 1,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_vai_tro_chi_nhanh
    ON tbl_sys_vai_tro_chi_nhanh (chi_nhanh_id, lower(ten_vai_tro))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_vai_tro_chi_nhanh_legacy_uuid
    ON tbl_sys_vai_tro_chi_nhanh (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_sys_vai_tro_chi_nhanh_quyen
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vai_tro_chi_nhanh_id bigint NOT NULL REFERENCES tbl_sys_vai_tro_chi_nhanh(auto_id) ON DELETE RESTRICT,
    ma_quyen varchar(120) NOT NULL,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_vai_tro_chi_nhanh_quyen
    ON tbl_sys_vai_tro_chi_nhanh_quyen (vai_tro_chi_nhanh_id, lower(ma_quyen))
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_sys_thanh_vien_chi_nhanh
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    vai_tro_chi_nhanh_id bigint NOT NULL REFERENCES tbl_sys_vai_tro_chi_nhanh(auto_id) ON DELETE RESTRICT,
    is_primary integer NOT NULL DEFAULT 0,
    is_hoat_dong integer NOT NULL DEFAULT 1,
    assigned_by_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_thanh_vien_chi_nhanh
    ON tbl_sys_thanh_vien_chi_nhanh (thanh_vien_id, chi_nhanh_id)
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_thanh_vien_chi_nhanh_legacy_uuid
    ON tbl_sys_thanh_vien_chi_nhanh (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_dm_kho_giay
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id integer NOT NULL,
    ma_kho_giay varchar(50) NOT NULL,
    ten_kho_giay varchar(100) NOT NULL,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_kho_giay_type
    ON tbl_dm_kho_giay (type_id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_dm_kieu_in
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id integer NOT NULL,
    ma_kieu_in varchar(50) NOT NULL,
    ten_kieu_in varchar(100) NOT NULL,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_kieu_in_type
    ON tbl_dm_kieu_in (type_id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_dm_mau_in
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id integer NOT NULL,
    ma_mau_in varchar(50) NOT NULL,
    ten_mau_in varchar(100) NOT NULL,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_mau_in_type
    ON tbl_dm_mau_in (type_id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_dm_phuong_thuc_nhan
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id integer NOT NULL,
    ma_phuong_thuc varchar(50) NOT NULL,
    ten_phuong_thuc varchar(100) NOT NULL,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_phuong_thuc_nhan_type
    ON tbl_dm_phuong_thuc_nhan (type_id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_dm_san_pham
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    ma_san_pham varchar(80) NOT NULL,
    ten_san_pham varchar(150) NOT NULL,
    mo_ta varchar(1000),
    don_gia numeric(18,2) NOT NULL DEFAULT 0,
    image_url varchar(500),
    is_hoat_dong integer NOT NULL DEFAULT 1,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_san_pham_code
    ON tbl_dm_san_pham (chi_nhanh_id, lower(ma_san_pham))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_san_pham_legacy_uuid
    ON tbl_dm_san_pham (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_dm_dich_vu_ho_tro
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    ma_dich_vu varchar(80) NOT NULL,
    ten_dich_vu varchar(150) NOT NULL,
    mo_ta varchar(1000),
    don_gia numeric(18,2) NOT NULL DEFAULT 0,
    loai_phi_id integer NOT NULL,
    is_hoat_dong integer NOT NULL DEFAULT 1,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_dich_vu_ho_tro_code
    ON tbl_dm_dich_vu_ho_tro (chi_nhanh_id, lower(ma_dich_vu))
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_dich_vu_ho_tro_legacy_uuid
    ON tbl_dm_dich_vu_ho_tro (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_dm_bang_gia_in
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    kho_giay_id bigint NOT NULL REFERENCES tbl_dm_kho_giay(auto_id) ON DELETE RESTRICT,
    kieu_in_id bigint NOT NULL REFERENCES tbl_dm_kieu_in(auto_id) ON DELETE RESTRICT,
    mau_in_id bigint NOT NULL REFERENCES tbl_dm_mau_in(auto_id) ON DELETE RESTRICT,
    is_photo integer NOT NULL DEFAULT 0,
    don_gia numeric(18,2) NOT NULL DEFAULT 0,
    is_hoat_dong integer NOT NULL DEFAULT 1,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_bang_gia_in_key
    ON tbl_dm_bang_gia_in (chi_nhanh_id, kho_giay_id, kieu_in_id, mau_in_id, is_photo)
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_dm_bang_gia_in_legacy_uuid
    ON tbl_dm_bang_gia_in (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_file_upload
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    ten_file_goc varchar(260) NOT NULL,
    ten_file_luu varchar(260) NOT NULL,
    duong_dan_tuong_doi varchar(500) NOT NULL,
    dung_luong_byte bigint NOT NULL DEFAULT 0,
    content_type varchar(100) NOT NULL,
    is_file_don_in integer NOT NULL DEFAULT 0,
    owner_identity_user_id varchar(191),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_file_upload_legacy_uuid
    ON tbl_tc_file_upload (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_vi_chi_nhanh
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    so_du numeric(18,2) NOT NULL DEFAULT 0,
    version_no bigint NOT NULL DEFAULT 1,
    identity_user_id varchar(191),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_tc_vi_chi_nhanh_so_du CHECK (so_du >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_vi_chi_nhanh_user_branch
    ON tbl_tc_vi_chi_nhanh (chi_nhanh_id, thanh_vien_id)
    WHERE deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_vi_chi_nhanh_legacy_uuid
    ON tbl_tc_vi_chi_nhanh (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_giao_dich_vi
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    vi_chi_nhanh_id bigint NOT NULL REFERENCES tbl_tc_vi_chi_nhanh(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    thuc_hien_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    loai_giao_dich_id integer NOT NULL,
    so_tien numeric(18,2) NOT NULL,
    so_du_truoc numeric(18,2) NOT NULL,
    so_du_sau numeric(18,2) NOT NULL,
    ref_type varchar(100),
    ref_id bigint,
    ref_legacy_uuid uuid,
    ghi_chu varchar(500),
    idempotency_key varchar(120),
    identity_user_id varchar(191),
    performed_by_identity_user_id varchar(191),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_tc_giao_dich_vi_balance CHECK (so_du_sau = so_du_truoc + so_tien)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_giao_dich_vi_idempotency
    ON tbl_tc_giao_dich_vi (chi_nhanh_id, thanh_vien_id, loai_giao_dich_id, lower(idempotency_key))
    WHERE deleted = 0 AND idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_giao_dich_vi_legacy_uuid
    ON tbl_tc_giao_dich_vi (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_yeu_cau_nap_tien
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    file_minh_chung_id bigint REFERENCES tbl_tc_file_upload(auto_id) ON DELETE RESTRICT,
    duyet_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    admin_duyet_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    giao_dich_vi_duyet_id bigint REFERENCES tbl_tc_giao_dich_vi(auto_id) ON DELETE RESTRICT,
    so_tien numeric(18,2) NOT NULL,
    noi_dung_chuyen_khoan varchar(200),
    ma_giao_dich varchar(100),
    create_idempotency_key varchar(120),
    last_review_idempotency_key varchar(120),
    kenh_nap_id integer NOT NULL,
    trang_thai_id integer NOT NULL,
    is_can_admin_duyet integer NOT NULL DEFAULT 0,
    ngay_gio_duyet timestamptz,
    ghi_chu_duyet varchar(500),
    ngay_gio_admin_duyet timestamptz,
    ghi_chu_admin_duyet varchar(500),
    identity_user_id varchar(191),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_tc_yeu_cau_nap_tien_amount CHECK (so_tien > 0),
    CONSTRAINT ck_tbl_tc_yeu_cau_nap_tien_two_reviewer CHECK (
        admin_duyet_boi_thanh_vien_id IS NULL
        OR duyet_boi_thanh_vien_id IS NULL
        OR admin_duyet_boi_thanh_vien_id <> duyet_boi_thanh_vien_id
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_yeu_cau_nap_tien_idempotency
    ON tbl_tc_yeu_cau_nap_tien (chi_nhanh_id, thanh_vien_id, kenh_nap_id, lower(create_idempotency_key))
    WHERE deleted = 0 AND create_idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_yeu_cau_nap_tien_legacy_uuid
    ON tbl_tc_yeu_cau_nap_tien (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_don_in
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    file_upload_id bigint NOT NULL REFERENCES tbl_tc_file_upload(auto_id) ON DELETE RESTRICT,
    kho_giay_id bigint NOT NULL REFERENCES tbl_dm_kho_giay(auto_id) ON DELETE RESTRICT,
    kieu_in_id bigint NOT NULL REFERENCES tbl_dm_kieu_in(auto_id) ON DELETE RESTRICT,
    mau_in_id bigint NOT NULL REFERENCES tbl_dm_mau_in(auto_id) ON DELETE RESTRICT,
    phuong_thuc_nhan_id bigint NOT NULL REFERENCES tbl_dm_phuong_thuc_nhan(auto_id) ON DELETE RESTRICT,
    xac_nhan_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    phan_cong_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    giao_dich_vi_thanh_toan_id bigint REFERENCES tbl_tc_giao_dich_vi(auto_id) ON DELETE RESTRICT,
    xu_ly_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    hoan_tien_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    is_photo integer NOT NULL DEFAULT 0,
    so_ban integer NOT NULL,
    so_trang integer NOT NULL,
    ghi_chu varchar(500),
    dia_chi_giao varchar(500),
    don_gia numeric(18,2) NOT NULL,
    thanh_tien numeric(18,2) NOT NULL,
    phi_giao_hang numeric(18,2) NOT NULL DEFAULT 0,
    tong_tien numeric(18,2) NOT NULL,
    trang_thai_id integer NOT NULL,
    ngay_gio_xac_nhan timestamptz,
    ghi_chu_trang_thai_cuoi varchar(500),
    ngay_gio_thanh_toan timestamptz,
    submit_idempotency_key varchar(120),
    ngay_gio_hoan_tien timestamptz,
    ly_do_hoan_tien varchar(500),
    identity_user_id varchar(191),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_tc_don_in_quantity CHECK (so_ban > 0 AND so_trang > 0),
    CONSTRAINT ck_tbl_tc_don_in_amount CHECK (tong_tien = thanh_tien + phi_giao_hang)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_don_in_idempotency
    ON tbl_tc_don_in (chi_nhanh_id, thanh_vien_id, lower(submit_idempotency_key))
    WHERE deleted = 0 AND submit_idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_don_in_legacy_uuid
    ON tbl_tc_don_in (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_don_hang_san_pham
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    xu_ly_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    phuong_thuc_nhan_id bigint NOT NULL REFERENCES tbl_dm_phuong_thuc_nhan(auto_id) ON DELETE RESTRICT,
    tong_tien numeric(18,2) NOT NULL,
    dia_chi_giao varchar(500),
    ghi_chu varchar(500),
    order_idempotency_key varchar(120),
    trang_thai_id integer NOT NULL,
    ngay_gio_xu_ly timestamptz,
    ghi_chu_xu_ly varchar(500),
    identity_user_id varchar(191),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_don_hang_san_pham_idempotency
    ON tbl_tc_don_hang_san_pham (chi_nhanh_id, thanh_vien_id, lower(order_idempotency_key))
    WHERE deleted = 0 AND order_idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_don_hang_san_pham_legacy_uuid
    ON tbl_tc_don_hang_san_pham (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_don_hang_san_pham_chi_tiet
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    don_hang_san_pham_id bigint NOT NULL REFERENCES tbl_tc_don_hang_san_pham(auto_id) ON DELETE RESTRICT,
    san_pham_id bigint NOT NULL REFERENCES tbl_dm_san_pham(auto_id) ON DELETE RESTRICT,
    so_luong integer NOT NULL,
    don_gia numeric(18,2) NOT NULL,
    thanh_tien numeric(18,2) NOT NULL,
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_tc_don_hang_san_pham_chi_tiet_quantity CHECK (so_luong > 0),
    CONSTRAINT ck_tbl_tc_don_hang_san_pham_chi_tiet_amount CHECK (thanh_tien = don_gia * so_luong)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_don_hang_san_pham_chi_tiet_legacy_uuid
    ON tbl_tc_don_hang_san_pham_chi_tiet (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_tc_don_dich_vu_ho_tro
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    thanh_vien_id bigint NOT NULL REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    dich_vu_ho_tro_id bigint NOT NULL REFERENCES tbl_dm_dich_vu_ho_tro(auto_id) ON DELETE RESTRICT,
    xu_ly_boi_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    so_luong integer NOT NULL,
    don_gia numeric(18,2) NOT NULL,
    tong_tien numeric(18,2) NOT NULL,
    ghi_chu varchar(500),
    order_idempotency_key varchar(120),
    trang_thai_id integer NOT NULL,
    ngay_gio_xu_ly timestamptz,
    ghi_chu_xu_ly varchar(500),
    identity_user_id varchar(191),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_tc_don_dich_vu_ho_tro_quantity CHECK (so_luong > 0),
    CONSTRAINT ck_tbl_tc_don_dich_vu_ho_tro_amount CHECK (tong_tien = don_gia * so_luong)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_don_dich_vu_ho_tro_idempotency
    ON tbl_tc_don_dich_vu_ho_tro (chi_nhanh_id, thanh_vien_id, lower(order_idempotency_key))
    WHERE deleted = 0 AND order_idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_tc_don_dich_vu_ho_tro_legacy_uuid
    ON tbl_tc_don_dich_vu_ho_tro (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_xnk_ton_kho_san_pham
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    san_pham_id bigint NOT NULL REFERENCES tbl_dm_san_pham(auto_id) ON DELETE RESTRICT,
    key_lo_hang varchar(300) NOT NULL DEFAULT '',
    lpn_id bigint NOT NULL DEFAULT 0,
    carton_id bigint NOT NULL DEFAULT 0,
    vi_tri_id bigint NOT NULL DEFAULT 0,
    trang_thai_lo_hang_id integer NOT NULL DEFAULT 1,
    so_luong_ton integer NOT NULL DEFAULT 0,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_xnk_ton_kho_san_pham_quantity CHECK (so_luong_ton >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_xnk_ton_kho_san_pham_key
    ON tbl_xnk_ton_kho_san_pham (chi_nhanh_id, san_pham_id, key_lo_hang, lpn_id, carton_id, vi_tri_id, trang_thai_lo_hang_id)
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_xnk_nhap_xuat_san_pham
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chi_nhanh_id bigint NOT NULL REFERENCES tbl_dm_chi_nhanh(auto_id) ON DELETE RESTRICT,
    san_pham_id bigint NOT NULL REFERENCES tbl_dm_san_pham(auto_id) ON DELETE RESTRICT,
    actor_thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    ton_kho_san_pham_id bigint REFERENCES tbl_xnk_ton_kho_san_pham(auto_id) ON DELETE RESTRICT,
    loai_nhap_xuat_id integer NOT NULL,
    so_luong_thay_doi integer NOT NULL,
    ton_truoc integer NOT NULL,
    ton_sau integer NOT NULL,
    ref_type varchar(100),
    ref_id bigint,
    ghi_chu varchar(500),
    key_lo_hang varchar(300) NOT NULL DEFAULT '',
    so_po varchar(100),
    so_batch varchar(100),
    so_lot varchar(100),
    so_serial varchar(100),
    ngay_san_xuat date,
    ngay_het_han date,
    line_item varchar(100),
    legacy_uuid uuid,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150),
    CONSTRAINT ck_tbl_xnk_nhap_xuat_san_pham_stock CHECK (ton_sau = ton_truoc + so_luong_thay_doi),
    CONSTRAINT ck_tbl_xnk_nhap_xuat_san_pham_non_negative CHECK (ton_sau >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_xnk_nhap_xuat_san_pham_legacy_uuid
    ON tbl_xnk_nhap_xuat_san_pham (legacy_uuid)
    WHERE legacy_uuid IS NOT NULL;

CREATE TABLE IF NOT EXISTS tbl_sys_grid_field
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_chuc_nang varchar(100) NOT NULL,
    ten_grid varchar(100) NOT NULL,
    ten_field varchar(150) NOT NULL,
    tieu_de varchar(200),
    do_rong integer,
    sort_order integer NOT NULL DEFAULT 0,
    is_hien_thi integer NOT NULL DEFAULT 1,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE TABLE IF NOT EXISTS tbl_sys_import_excel_template_config
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_chuc_nang varchar(100) NOT NULL,
    ten_template varchar(200) NOT NULL,
    file_template_url varchar(500),
    is_hoat_dong integer NOT NULL DEFAULT 1,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE TABLE IF NOT EXISTS tbl_sys_report_template_config
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_chuc_nang varchar(100) NOT NULL,
    ma_report varchar(100) NOT NULL,
    ten_report varchar(200) NOT NULL,
    file_template_url varchar(500),
    is_hoat_dong integer NOT NULL DEFAULT 1,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE TABLE IF NOT EXISTS tbl_sys_webhook
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_webhook varchar(100) NOT NULL,
    ten_webhook varchar(200) NOT NULL,
    url varchar(1000),
    secret_key varchar(500),
    is_hoat_dong integer NOT NULL DEFAULT 1,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_webhook_ma
    ON tbl_sys_webhook (lower(ma_webhook))
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_sys_api_source
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_api_source varchar(100) NOT NULL,
    ten_api_source varchar(200) NOT NULL,
    base_url varchar(1000),
    is_hoat_dong integer NOT NULL DEFAULT 1,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_api_source_ma
    ON tbl_sys_api_source (lower(ma_api_source))
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_sys_auto_thread
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_thread varchar(100) NOT NULL,
    ten_thread varchar(200) NOT NULL,
    cron_expression varchar(100),
    is_hoat_dong integer NOT NULL DEFAULT 1,
    last_run_at timestamptz,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_auto_thread_ma
    ON tbl_sys_auto_thread (lower(ma_thread))
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_sys_stt_next
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_chuc_nang varchar(100) NOT NULL,
    prefix varchar(50) NOT NULL,
    next_no bigint NOT NULL DEFAULT 1,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbl_sys_stt_next_key
    ON tbl_sys_stt_next (lower(ma_chuc_nang), lower(prefix))
    WHERE deleted = 0;

CREATE TABLE IF NOT EXISTS tbl_log_record_action_history
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_id bigint NOT NULL,
    ten_hanh_dong varchar(150) NOT NULL,
    ten_moi_truong varchar(150),
    ma_chuc_nang varchar(100),
    ten_chuc_nang varchar(200),
    noi_dung_action text,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE TABLE IF NOT EXISTS tbl_log_api
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name varchar(150),
    endpoint varchar(500),
    method varchar(20),
    status_code integer,
    request_body text,
    response_body text,
    error_message text,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE TABLE IF NOT EXISTS tbl_log_nhat_ky_dang_nhap
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thanh_vien_id bigint REFERENCES tbl_sys_thanh_vien(auto_id) ON DELETE RESTRICT,
    ma_dang_nhap varchar(256),
    ip_address varchar(100),
    user_agent varchar(1000),
    is_success integer NOT NULL DEFAULT 0,
    message varchar(500),
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE TABLE IF NOT EXISTS tbl_log_import_excel
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_chuc_nang varchar(100),
    ten_file varchar(260),
    total_rows integer NOT NULL DEFAULT 0,
    success_rows integer NOT NULL DEFAULT 0,
    error_rows integer NOT NULL DEFAULT 0,
    error_text text,
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE TABLE IF NOT EXISTS tbl_log_export_excel
(
    auto_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_chuc_nang varchar(100),
    ten_file varchar(260),
    total_rows integer NOT NULL DEFAULT 0,
    file_url varchar(500),
    deleted integer NOT NULL DEFAULT 0,
    created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(100),
    last_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_by varchar(100),
    created_by_function varchar(150),
    last_updated_by_function varchar(150)
);

CREATE OR REPLACE TRIGGER trg_tbl_dm_chi_nhanh_tracking BEFORE INSERT OR UPDATE ON tbl_dm_chi_nhanh FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_thanh_vien_tracking BEFORE INSERT OR UPDATE ON tbl_sys_thanh_vien FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_nhom_thanh_vien_tracking BEFORE INSERT OR UPDATE ON tbl_sys_nhom_thanh_vien FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_nhom_thanh_vien_user_tracking BEFORE INSERT OR UPDATE ON tbl_sys_nhom_thanh_vien_user FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_chuc_nang_tracking BEFORE INSERT OR UPDATE ON tbl_sys_chuc_nang FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_phan_quyen_chuc_nang_tracking BEFORE INSERT OR UPDATE ON tbl_sys_phan_quyen_chuc_nang FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_chi_nhanh_tinh_nang_tracking BEFORE INSERT OR UPDATE ON tbl_sys_chi_nhanh_tinh_nang FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_vai_tro_chi_nhanh_tracking BEFORE INSERT OR UPDATE ON tbl_sys_vai_tro_chi_nhanh FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_vai_tro_chi_nhanh_quyen_tracking BEFORE INSERT OR UPDATE ON tbl_sys_vai_tro_chi_nhanh_quyen FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_thanh_vien_chi_nhanh_tracking BEFORE INSERT OR UPDATE ON tbl_sys_thanh_vien_chi_nhanh FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_dm_kho_giay_tracking BEFORE INSERT OR UPDATE ON tbl_dm_kho_giay FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_dm_kieu_in_tracking BEFORE INSERT OR UPDATE ON tbl_dm_kieu_in FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_dm_mau_in_tracking BEFORE INSERT OR UPDATE ON tbl_dm_mau_in FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_dm_phuong_thuc_nhan_tracking BEFORE INSERT OR UPDATE ON tbl_dm_phuong_thuc_nhan FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_dm_san_pham_tracking BEFORE INSERT OR UPDATE ON tbl_dm_san_pham FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_dm_dich_vu_ho_tro_tracking BEFORE INSERT OR UPDATE ON tbl_dm_dich_vu_ho_tro FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_dm_bang_gia_in_tracking BEFORE INSERT OR UPDATE ON tbl_dm_bang_gia_in FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_file_upload_tracking BEFORE INSERT OR UPDATE ON tbl_tc_file_upload FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_vi_chi_nhanh_tracking BEFORE INSERT OR UPDATE ON tbl_tc_vi_chi_nhanh FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_giao_dich_vi_tracking BEFORE INSERT OR UPDATE ON tbl_tc_giao_dich_vi FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_yeu_cau_nap_tien_tracking BEFORE INSERT OR UPDATE ON tbl_tc_yeu_cau_nap_tien FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_don_in_tracking BEFORE INSERT OR UPDATE ON tbl_tc_don_in FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_don_hang_san_pham_tracking BEFORE INSERT OR UPDATE ON tbl_tc_don_hang_san_pham FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_don_hang_san_pham_chi_tiet_tracking BEFORE INSERT OR UPDATE ON tbl_tc_don_hang_san_pham_chi_tiet FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_tc_don_dich_vu_ho_tro_tracking BEFORE INSERT OR UPDATE ON tbl_tc_don_dich_vu_ho_tro FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_xnk_ton_kho_san_pham_tracking BEFORE INSERT OR UPDATE ON tbl_xnk_ton_kho_san_pham FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_xnk_nhap_xuat_san_pham_tracking BEFORE INSERT OR UPDATE ON tbl_xnk_nhap_xuat_san_pham FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_grid_field_tracking BEFORE INSERT OR UPDATE ON tbl_sys_grid_field FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_import_excel_template_config_tracking BEFORE INSERT OR UPDATE ON tbl_sys_import_excel_template_config FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_report_template_config_tracking BEFORE INSERT OR UPDATE ON tbl_sys_report_template_config FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_webhook_tracking BEFORE INSERT OR UPDATE ON tbl_sys_webhook FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_api_source_tracking BEFORE INSERT OR UPDATE ON tbl_sys_api_source FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_auto_thread_tracking BEFORE INSERT OR UPDATE ON tbl_sys_auto_thread FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_sys_stt_next_tracking BEFORE INSERT OR UPDATE ON tbl_sys_stt_next FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_log_record_action_history_tracking BEFORE INSERT OR UPDATE ON tbl_log_record_action_history FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_log_api_tracking BEFORE INSERT OR UPDATE ON tbl_log_api FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_log_nhat_ky_dang_nhap_tracking BEFORE INSERT OR UPDATE ON tbl_log_nhat_ky_dang_nhap FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_log_import_excel_tracking BEFORE INSERT OR UPDATE ON tbl_log_import_excel FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();
CREATE OR REPLACE TRIGGER trg_tbl_log_export_excel_tracking BEFORE INSERT OR UPDATE ON tbl_log_export_excel FOR EACH ROW EXECUTE FUNCTION fn_tks_set_tracking_columns();

INSERT INTO tbl_dm_kho_giay (type_id, ma_kho_giay, ten_kho_giay, created_by_function, last_updated_by_function)
VALUES
    (1, 'A5', 'A5', 'V20260704_001_seed', 'V20260704_001_seed'),
    (2, 'A4', 'A4', 'V20260704_001_seed', 'V20260704_001_seed'),
    (3, 'A3', 'A3', 'V20260704_001_seed', 'V20260704_001_seed'),
    (4, 'A0', 'A0', 'V20260704_001_seed', 'V20260704_001_seed')
ON CONFLICT (type_id) WHERE deleted = 0 DO UPDATE
SET ma_kho_giay = EXCLUDED.ma_kho_giay,
    ten_kho_giay = EXCLUDED.ten_kho_giay,
    last_updated_by_function = EXCLUDED.last_updated_by_function;

INSERT INTO tbl_dm_kieu_in (type_id, ma_kieu_in, ten_kieu_in, created_by_function, last_updated_by_function)
VALUES
    (1, 'ONE_SIDE', 'Một mặt', 'V20260704_001_seed', 'V20260704_001_seed'),
    (2, 'TWO_SIDE', 'Hai mặt', 'V20260704_001_seed', 'V20260704_001_seed')
ON CONFLICT (type_id) WHERE deleted = 0 DO UPDATE
SET ma_kieu_in = EXCLUDED.ma_kieu_in,
    ten_kieu_in = EXCLUDED.ten_kieu_in,
    last_updated_by_function = EXCLUDED.last_updated_by_function;

INSERT INTO tbl_dm_mau_in (type_id, ma_mau_in, ten_mau_in, created_by_function, last_updated_by_function)
VALUES
    (1, 'BLACK_WHITE', 'Trắng đen', 'V20260704_001_seed', 'V20260704_001_seed'),
    (2, 'COLOR', 'Màu', 'V20260704_001_seed', 'V20260704_001_seed')
ON CONFLICT (type_id) WHERE deleted = 0 DO UPDATE
SET ma_mau_in = EXCLUDED.ma_mau_in,
    ten_mau_in = EXCLUDED.ten_mau_in,
    last_updated_by_function = EXCLUDED.last_updated_by_function;

INSERT INTO tbl_dm_phuong_thuc_nhan (type_id, ma_phuong_thuc, ten_phuong_thuc, created_by_function, last_updated_by_function)
VALUES
    (1, 'PICKUP_AT_STORE', 'Nhận tại quầy', 'V20260704_001_seed', 'V20260704_001_seed'),
    (2, 'SHIPPING', 'Giao hàng', 'V20260704_001_seed', 'V20260704_001_seed')
ON CONFLICT (type_id) WHERE deleted = 0 DO UPDATE
SET ma_phuong_thuc = EXCLUDED.ma_phuong_thuc,
    ten_phuong_thuc = EXCLUDED.ten_phuong_thuc,
    last_updated_by_function = EXCLUDED.last_updated_by_function;

CREATE OR REPLACE VIEW view_dm_chi_nhanh
AS
    SELECT
        a.auto_id,
        a.ma_chi_nhanh,
        a.slug,
        a.ten_chi_nhanh,
        a.dia_chi,
        a.dien_thoai,
        a.email,
        a.gio_mo_cua,
        a.mo_ta_ngan,
        a.ghi_chu_khach_hang,
        a.dich_vu_pho_bien_text,
        a.tuy_chon_nhanh_text,
        a.is_hoat_dong,
        a.is_nhan_don,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_dm_chi_nhanh a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_dm_san_pham
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_san_pham,
        a.ten_san_pham,
        a.mo_ta,
        a.don_gia,
        a.image_url,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_dm_san_pham a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_dm_dich_vu_ho_tro
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_dich_vu,
        a.ten_dich_vu,
        a.mo_ta,
        a.don_gia,
        a.loai_phi_id,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_dm_dich_vu_ho_tro a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_dm_bang_gia_in
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.kho_giay_id,
        a.kieu_in_id,
        a.mau_in_id,
        a.is_photo,
        a.don_gia,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_dm_bang_gia_in a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_tc_vi_chi_nhanh
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        a.so_du,
        a.version_no,
        a.identity_user_id,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_tc_vi_chi_nhanh a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_tc_giao_dich_vi
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.vi_chi_nhanh_id,
        a.thanh_vien_id,
        a.thuc_hien_boi_thanh_vien_id,
        a.loai_giao_dich_id,
        a.so_tien,
        a.so_du_truoc,
        a.so_du_sau,
        a.ref_type,
        a.ref_id,
        a.ref_legacy_uuid,
        a.ghi_chu,
        a.idempotency_key,
        a.identity_user_id,
        a.performed_by_identity_user_id,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_tc_giao_dich_vi a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_tc_don_in
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        a.file_upload_id,
        a.kho_giay_id,
        a.kieu_in_id,
        a.mau_in_id,
        a.phuong_thuc_nhan_id,
        a.is_photo,
        a.so_ban,
        a.so_trang,
        a.ghi_chu,
        a.dia_chi_giao,
        a.don_gia,
        a.thanh_tien,
        a.phi_giao_hang,
        a.tong_tien,
        a.trang_thai_id,
        a.submit_idempotency_key,
        a.identity_user_id,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_tc_don_in a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_tc_don_hang_san_pham
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        a.xu_ly_boi_thanh_vien_id,
        a.phuong_thuc_nhan_id,
        a.tong_tien,
        a.dia_chi_giao,
        a.ghi_chu,
        a.order_idempotency_key,
        a.trang_thai_id,
        a.ngay_gio_xu_ly,
        a.ghi_chu_xu_ly,
        a.identity_user_id,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_tc_don_hang_san_pham a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_tc_don_dich_vu_ho_tro
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        a.dich_vu_ho_tro_id,
        a.xu_ly_boi_thanh_vien_id,
        a.so_luong,
        a.don_gia,
        a.tong_tien,
        a.ghi_chu,
        a.order_idempotency_key,
        a.trang_thai_id,
        a.identity_user_id,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_tc_don_dich_vu_ho_tro a
    WHERE a.deleted = 0;

CREATE OR REPLACE VIEW view_xnk_ton_kho_san_pham
AS
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.san_pham_id,
        a.key_lo_hang,
        a.lpn_id,
        a.carton_id,
        a.vi_tri_id,
        a.trang_thai_lo_hang_id,
        a.so_luong_ton,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_xnk_ton_kho_san_pham a
    WHERE a.deleted = 0;

CREATE OR REPLACE FUNCTION fq_100_cn_sp_sel_list_by_created(p_dtm_from timestamptz, p_dtm_to timestamptz)
RETURNS SETOF view_dm_chi_nhanh
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.ma_chi_nhanh,
        a.slug,
        a.ten_chi_nhanh,
        a.dia_chi,
        a.dien_thoai,
        a.email,
        a.gio_mo_cua,
        a.mo_ta_ngan,
        a.ghi_chu_khach_hang,
        a.dich_vu_pho_bien_text,
        a.tuy_chon_nhanh_text,
        a.is_hoat_dong,
        a.is_nhan_don,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_chi_nhanh a
    WHERE a.created >= p_dtm_from
        AND a.created <= p_dtm_to
    ORDER BY a.created DESC;
$$;

CREATE OR REPLACE FUNCTION fq_100_cn_sp_sel_list_for_cache()
RETURNS SETOF view_dm_chi_nhanh
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.ma_chi_nhanh,
        a.slug,
        a.ten_chi_nhanh,
        a.dia_chi,
        a.dien_thoai,
        a.email,
        a.gio_mo_cua,
        a.mo_ta_ngan,
        a.ghi_chu_khach_hang,
        a.dich_vu_pho_bien_text,
        a.tuy_chon_nhanh_text,
        a.is_hoat_dong,
        a.is_nhan_don,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_chi_nhanh a
    ORDER BY a.ten_chi_nhanh;
$$;

CREATE OR REPLACE FUNCTION fq_100_cn_sp_sel_get_by_id(p_i_auto_id bigint)
RETURNS view_dm_chi_nhanh
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.ma_chi_nhanh,
        a.slug,
        a.ten_chi_nhanh,
        a.dia_chi,
        a.dien_thoai,
        a.email,
        a.gio_mo_cua,
        a.mo_ta_ngan,
        a.ghi_chu_khach_hang,
        a.dich_vu_pho_bien_text,
        a.tuy_chon_nhanh_text,
        a.is_hoat_dong,
        a.is_nhan_don,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_chi_nhanh a
    WHERE a.auto_id = p_i_auto_id;
$$;

CREATE OR REPLACE FUNCTION fq_100_cn_sp_ins_insert(
    p_str_ma_chi_nhanh varchar,
    p_str_slug varchar,
    p_str_ten_chi_nhanh varchar,
    p_str_dia_chi varchar,
    p_str_dien_thoai varchar,
    p_str_email varchar,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_i_auto_id bigint;
BEGIN
    INSERT INTO tbl_dm_chi_nhanh
    (
        ma_chi_nhanh,
        slug,
        ten_chi_nhanh,
        dia_chi,
        dien_thoai,
        email,
        created_by,
        last_updated_by,
        created_by_function,
        last_updated_by_function
    )
    VALUES
    (
        trim(p_str_ma_chi_nhanh),
        trim(p_str_slug),
        trim(p_str_ten_chi_nhanh),
        p_str_dia_chi,
        p_str_dien_thoai,
        p_str_email,
        p_str_last_updated_by,
        p_str_last_updated_by,
        p_str_last_updated_by_function,
        p_str_last_updated_by_function
    )
    RETURNING auto_id INTO v_i_auto_id;

    RETURN v_i_auto_id;
END;
$$;

CREATE OR REPLACE FUNCTION fq_100_cn_sp_upd_update(
    p_i_auto_id bigint,
    p_str_ma_chi_nhanh varchar,
    p_str_slug varchar,
    p_str_ten_chi_nhanh varchar,
    p_str_dia_chi varchar,
    p_str_dien_thoai varchar,
    p_str_email varchar,
    p_i_is_hoat_dong integer,
    p_i_is_nhan_don integer,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_chi_nhanh
    SET ma_chi_nhanh = trim(p_str_ma_chi_nhanh),
        slug = trim(p_str_slug),
        ten_chi_nhanh = trim(p_str_ten_chi_nhanh),
        dia_chi = p_str_dia_chi,
        dien_thoai = p_str_dien_thoai,
        email = p_str_email,
        is_hoat_dong = p_i_is_hoat_dong,
        is_nhan_don = p_i_is_nhan_don,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE FUNCTION fq_100_cn_sp_del_delete_by_id(
    p_i_auto_id bigint,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_chi_nhanh
    SET deleted = 1,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE VIEW view_sys_thanh_vien
AS
    SELECT
        a.auto_id,
        a.ma_dang_nhap,
        a.email,
        a.ho_ten,
        a.dia_chi,
        a.dien_thoai,
        a.current_balance_legacy,
        a.is_hoat_dong,
        a.identity_user_id,
        a.legacy_id,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM tbl_sys_thanh_vien a
    WHERE a.deleted = 0;

CREATE OR REPLACE FUNCTION fq_101_tv_sp_sel_get_by_identity_user_id(p_str_identity_user_id varchar)
RETURNS view_sys_thanh_vien
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.ma_dang_nhap,
        a.email,
        a.ho_ten,
        a.dia_chi,
        a.dien_thoai,
        a.current_balance_legacy,
        a.is_hoat_dong,
        a.identity_user_id,
        a.legacy_id,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_sys_thanh_vien a
    WHERE a.identity_user_id = p_str_identity_user_id;
$$;

CREATE OR REPLACE FUNCTION fq_200_sp_sp_sel_list_for_cache()
RETURNS SETOF view_dm_san_pham
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_san_pham,
        a.ten_san_pham,
        a.mo_ta,
        a.don_gia,
        a.image_url,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_san_pham a
    ORDER BY a.ten_san_pham;
$$;

CREATE OR REPLACE FUNCTION fq_200_sp_sp_ins_insert(
    p_i_chi_nhanh_id bigint,
    p_str_ma_san_pham varchar,
    p_str_ten_san_pham varchar,
    p_str_mo_ta varchar,
    p_dec_don_gia numeric,
    p_str_image_url varchar,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_i_auto_id bigint;
BEGIN
    INSERT INTO tbl_dm_san_pham
    (
        chi_nhanh_id,
        ma_san_pham,
        ten_san_pham,
        mo_ta,
        don_gia,
        image_url,
        created_by,
        last_updated_by,
        created_by_function,
        last_updated_by_function
    )
    VALUES
    (
        p_i_chi_nhanh_id,
        trim(p_str_ma_san_pham),
        trim(p_str_ten_san_pham),
        p_str_mo_ta,
        p_dec_don_gia,
        p_str_image_url,
        p_str_last_updated_by,
        p_str_last_updated_by,
        p_str_last_updated_by_function,
        p_str_last_updated_by_function
    )
    RETURNING auto_id INTO v_i_auto_id;

    INSERT INTO tbl_xnk_ton_kho_san_pham
    (
        chi_nhanh_id,
        san_pham_id,
        key_lo_hang,
        so_luong_ton,
        created_by,
        last_updated_by,
        created_by_function,
        last_updated_by_function
    )
    VALUES
    (
        p_i_chi_nhanh_id,
        v_i_auto_id,
        '',
        0,
        p_str_last_updated_by,
        p_str_last_updated_by,
        p_str_last_updated_by_function,
        p_str_last_updated_by_function
    );

    RETURN v_i_auto_id;
END;
$$;

CREATE OR REPLACE FUNCTION fq_201_dvht_sp_sel_list_for_cache()
RETURNS SETOF view_dm_dich_vu_ho_tro
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_dich_vu,
        a.ten_dich_vu,
        a.mo_ta,
        a.don_gia,
        a.loai_phi_id,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_dich_vu_ho_tro a
    ORDER BY a.ten_dich_vu;
$$;

CREATE OR REPLACE FUNCTION fq_202_bgi_sp_sel_list_for_cache()
RETURNS SETOF view_dm_bang_gia_in
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.kho_giay_id,
        a.kieu_in_id,
        a.mau_in_id,
        a.is_photo,
        a.don_gia,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_bang_gia_in a
    ORDER BY a.chi_nhanh_id,
        a.kho_giay_id,
        a.kieu_in_id,
        a.mau_in_id,
        a.is_photo;
$$;

CREATE OR REPLACE FUNCTION f2002_sp_sel_get_so_du_vi(
    p_i_chi_nhanh_id bigint,
    p_i_thanh_vien_id bigint
)
RETURNS numeric(18,2)
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE((
        SELECT a.so_du
        FROM tbl_tc_vi_chi_nhanh a
        WHERE a.deleted = 0
            AND a.chi_nhanh_id = p_i_chi_nhanh_id
            AND a.thanh_vien_id = p_i_thanh_vien_id
        LIMIT 1
    ), 0)::numeric(18,2);
$$;

CREATE OR REPLACE FUNCTION f2002_sp_ins_giao_dich_vi(
    p_i_chi_nhanh_id bigint,
    p_i_thanh_vien_id bigint,
    p_i_loai_giao_dich_id integer,
    p_dec_so_tien numeric,
    p_str_ref_type varchar,
    p_i_ref_id bigint,
    p_str_ghi_chu varchar,
    p_str_idempotency_key varchar,
    p_i_thuc_hien_boi_thanh_vien_id bigint,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_i_vi_chi_nhanh_id bigint;
    v_dec_so_du_truoc numeric(18,2);
    v_dec_so_du_sau numeric(18,2);
    v_i_existing_auto_id bigint;
    v_i_auto_id bigint;
BEGIN
    IF p_str_idempotency_key IS NOT NULL THEN
        SELECT a.auto_id
        INTO v_i_existing_auto_id
        FROM tbl_tc_giao_dich_vi a
        WHERE a.deleted = 0
            AND a.chi_nhanh_id = p_i_chi_nhanh_id
            AND a.thanh_vien_id = p_i_thanh_vien_id
            AND a.loai_giao_dich_id = p_i_loai_giao_dich_id
            AND lower(a.idempotency_key) = lower(p_str_idempotency_key)
        LIMIT 1;

        IF v_i_existing_auto_id IS NOT NULL THEN
            RETURN v_i_existing_auto_id;
        END IF;
    END IF;

    SELECT a.auto_id,
        a.so_du
    INTO v_i_vi_chi_nhanh_id,
        v_dec_so_du_truoc
    FROM tbl_tc_vi_chi_nhanh a
    WHERE a.deleted = 0
        AND a.chi_nhanh_id = p_i_chi_nhanh_id
        AND a.thanh_vien_id = p_i_thanh_vien_id
    FOR UPDATE;

    IF v_i_vi_chi_nhanh_id IS NULL THEN
        INSERT INTO tbl_tc_vi_chi_nhanh
        (
            chi_nhanh_id,
            thanh_vien_id,
            so_du,
            created_by,
            last_updated_by,
            created_by_function,
            last_updated_by_function
        )
        VALUES
        (
            p_i_chi_nhanh_id,
            p_i_thanh_vien_id,
            0,
            p_str_last_updated_by,
            p_str_last_updated_by,
            p_str_last_updated_by_function,
            p_str_last_updated_by_function
        )
        RETURNING auto_id,
            so_du
        INTO v_i_vi_chi_nhanh_id,
            v_dec_so_du_truoc;
    END IF;

    v_dec_so_du_sau := v_dec_so_du_truoc + p_dec_so_tien;

    IF v_dec_so_du_sau < 0 THEN
        RAISE EXCEPTION 'So du vi khong du.';
    END IF;

    UPDATE tbl_tc_vi_chi_nhanh
    SET so_du = v_dec_so_du_sau,
        version_no = version_no + 1,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = v_i_vi_chi_nhanh_id;

    INSERT INTO tbl_tc_giao_dich_vi
    (
        chi_nhanh_id,
        vi_chi_nhanh_id,
        thanh_vien_id,
        thuc_hien_boi_thanh_vien_id,
        loai_giao_dich_id,
        so_tien,
        so_du_truoc,
        so_du_sau,
        ref_type,
        ref_id,
        ghi_chu,
        idempotency_key,
        created_by,
        last_updated_by,
        created_by_function,
        last_updated_by_function
    )
    VALUES
    (
        p_i_chi_nhanh_id,
        v_i_vi_chi_nhanh_id,
        p_i_thanh_vien_id,
        p_i_thuc_hien_boi_thanh_vien_id,
        p_i_loai_giao_dich_id,
        p_dec_so_tien,
        v_dec_so_du_truoc,
        v_dec_so_du_sau,
        p_str_ref_type,
        p_i_ref_id,
        p_str_ghi_chu,
        p_str_idempotency_key,
        p_str_last_updated_by,
        p_str_last_updated_by,
        p_str_last_updated_by_function,
        p_str_last_updated_by_function
    )
    RETURNING auto_id INTO v_i_auto_id;

    RETURN v_i_auto_id;
END;
$$;

CREATE OR REPLACE FUNCTION f2002_sp_sel_list_giao_dich_vi_by_created(
    p_dtm_from timestamptz,
    p_dtm_to timestamptz
)
RETURNS SETOF view_tc_giao_dich_vi
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.vi_chi_nhanh_id,
        a.thanh_vien_id,
        a.thuc_hien_boi_thanh_vien_id,
        a.loai_giao_dich_id,
        a.so_tien,
        a.so_du_truoc,
        a.so_du_sau,
        a.ref_type,
        a.ref_id,
        a.ref_legacy_uuid,
        a.ghi_chu,
        a.idempotency_key,
        a.identity_user_id,
        a.performed_by_identity_user_id,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_tc_giao_dich_vi a
    WHERE a.created >= p_dtm_from
        AND a.created <= p_dtm_to
    ORDER BY a.created DESC;
$$;

CREATE OR REPLACE FUNCTION f2002_sp_sel_reconcile_vi_chi_nhanh()
RETURNS TABLE
(
    vi_chi_nhanh_id bigint,
    chi_nhanh_id bigint,
    thanh_vien_id bigint,
    so_du_hien_tai numeric(18,2),
    so_du_theo_giao_dich numeric(18,2),
    chenh_lech numeric(18,2)
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id AS vi_chi_nhanh_id,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        a.so_du AS so_du_hien_tai,
        COALESCE(SUM(b.so_tien), 0)::numeric(18,2) AS so_du_theo_giao_dich,
        (a.so_du - COALESCE(SUM(b.so_tien), 0))::numeric(18,2) AS chenh_lech
    FROM tbl_tc_vi_chi_nhanh a
    LEFT JOIN tbl_tc_giao_dich_vi b
        ON b.vi_chi_nhanh_id = a.auto_id
        AND b.deleted = 0
    WHERE a.deleted = 0
    GROUP BY
        a.auto_id,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        a.so_du;
$$;

CREATE OR REPLACE FUNCTION f2004_sp_ins_nhap_xuat_san_pham(
    p_i_chi_nhanh_id bigint,
    p_i_san_pham_id bigint,
    p_i_actor_thanh_vien_id bigint,
    p_i_loai_nhap_xuat_id integer,
    p_i_so_luong_thay_doi integer,
    p_str_ref_type varchar,
    p_i_ref_id bigint,
    p_str_ghi_chu varchar,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_i_ton_kho_san_pham_id bigint;
    v_i_ton_truoc integer;
    v_i_ton_sau integer;
    v_i_auto_id bigint;
BEGIN
    SELECT a.auto_id,
        a.so_luong_ton
    INTO v_i_ton_kho_san_pham_id,
        v_i_ton_truoc
    FROM tbl_xnk_ton_kho_san_pham a
    WHERE a.deleted = 0
        AND a.chi_nhanh_id = p_i_chi_nhanh_id
        AND a.san_pham_id = p_i_san_pham_id
        AND a.key_lo_hang = ''
        AND a.lpn_id = 0
        AND a.carton_id = 0
        AND a.vi_tri_id = 0
        AND a.trang_thai_lo_hang_id = 1
    FOR UPDATE;

    IF v_i_ton_kho_san_pham_id IS NULL THEN
        INSERT INTO tbl_xnk_ton_kho_san_pham
        (
            chi_nhanh_id,
            san_pham_id,
            key_lo_hang,
            so_luong_ton,
            created_by,
            last_updated_by,
            created_by_function,
            last_updated_by_function
        )
        VALUES
        (
            p_i_chi_nhanh_id,
            p_i_san_pham_id,
            '',
            0,
            p_str_last_updated_by,
            p_str_last_updated_by,
            p_str_last_updated_by_function,
            p_str_last_updated_by_function
        )
        RETURNING auto_id,
            so_luong_ton
        INTO v_i_ton_kho_san_pham_id,
            v_i_ton_truoc;
    END IF;

    v_i_ton_sau := v_i_ton_truoc + p_i_so_luong_thay_doi;

    IF v_i_ton_sau < 0 THEN
        RAISE EXCEPTION 'Ton kho san pham khong du.';
    END IF;

    UPDATE tbl_xnk_ton_kho_san_pham
    SET so_luong_ton = v_i_ton_sau,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = v_i_ton_kho_san_pham_id;

    INSERT INTO tbl_xnk_nhap_xuat_san_pham
    (
        chi_nhanh_id,
        san_pham_id,
        actor_thanh_vien_id,
        ton_kho_san_pham_id,
        loai_nhap_xuat_id,
        so_luong_thay_doi,
        ton_truoc,
        ton_sau,
        ref_type,
        ref_id,
        ghi_chu,
        created_by,
        last_updated_by,
        created_by_function,
        last_updated_by_function
    )
    VALUES
    (
        p_i_chi_nhanh_id,
        p_i_san_pham_id,
        p_i_actor_thanh_vien_id,
        v_i_ton_kho_san_pham_id,
        p_i_loai_nhap_xuat_id,
        p_i_so_luong_thay_doi,
        v_i_ton_truoc,
        v_i_ton_sau,
        p_str_ref_type,
        p_i_ref_id,
        p_str_ghi_chu,
        p_str_last_updated_by,
        p_str_last_updated_by,
        p_str_last_updated_by_function,
        p_str_last_updated_by_function
    )
    RETURNING auto_id INTO v_i_auto_id;

    RETURN v_i_auto_id;
END;
$$;

CREATE OR REPLACE FUNCTION fq_200_sp_sp_sel_list_by_created(p_dtm_from timestamptz, p_dtm_to timestamptz)
RETURNS SETOF view_dm_san_pham
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_san_pham,
        a.ten_san_pham,
        a.mo_ta,
        a.don_gia,
        a.image_url,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_san_pham a
    WHERE a.created >= p_dtm_from
        AND a.created <= p_dtm_to
    ORDER BY a.created DESC;
$$;

CREATE OR REPLACE FUNCTION fq_200_sp_sp_sel_get_by_id(p_i_auto_id bigint)
RETURNS view_dm_san_pham
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_san_pham,
        a.ten_san_pham,
        a.mo_ta,
        a.don_gia,
        a.image_url,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_san_pham a
    WHERE a.auto_id = p_i_auto_id;
$$;

CREATE OR REPLACE FUNCTION fq_200_sp_sp_upd_update(
    p_i_auto_id bigint,
    p_i_chi_nhanh_id bigint,
    p_str_ma_san_pham varchar,
    p_str_ten_san_pham varchar,
    p_str_mo_ta varchar,
    p_dec_don_gia numeric,
    p_str_image_url varchar,
    p_i_is_hoat_dong integer,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_san_pham
    SET chi_nhanh_id = p_i_chi_nhanh_id,
        ma_san_pham = trim(p_str_ma_san_pham),
        ten_san_pham = trim(p_str_ten_san_pham),
        mo_ta = p_str_mo_ta,
        don_gia = p_dec_don_gia,
        image_url = p_str_image_url,
        is_hoat_dong = p_i_is_hoat_dong,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE FUNCTION fq_200_sp_sp_del_delete_by_id(
    p_i_auto_id bigint,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_san_pham
    SET deleted = 1,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE FUNCTION fq_201_dvht_sp_sel_list_by_created(p_dtm_from timestamptz, p_dtm_to timestamptz)
RETURNS SETOF view_dm_dich_vu_ho_tro
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_dich_vu,
        a.ten_dich_vu,
        a.mo_ta,
        a.don_gia,
        a.loai_phi_id,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_dich_vu_ho_tro a
    WHERE a.created >= p_dtm_from
        AND a.created <= p_dtm_to
    ORDER BY a.created DESC;
$$;

CREATE OR REPLACE FUNCTION fq_201_dvht_sp_sel_get_by_id(p_i_auto_id bigint)
RETURNS view_dm_dich_vu_ho_tro
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.ma_dich_vu,
        a.ten_dich_vu,
        a.mo_ta,
        a.don_gia,
        a.loai_phi_id,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_dich_vu_ho_tro a
    WHERE a.auto_id = p_i_auto_id;
$$;

CREATE OR REPLACE FUNCTION fq_201_dvht_sp_ins_insert(
    p_i_chi_nhanh_id bigint,
    p_str_ma_dich_vu varchar,
    p_str_ten_dich_vu varchar,
    p_str_mo_ta varchar,
    p_dec_don_gia numeric,
    p_i_loai_phi_id integer,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_i_auto_id bigint;
BEGIN
    INSERT INTO tbl_dm_dich_vu_ho_tro
    (
        chi_nhanh_id,
        ma_dich_vu,
        ten_dich_vu,
        mo_ta,
        don_gia,
        loai_phi_id,
        created_by,
        last_updated_by,
        created_by_function,
        last_updated_by_function
    )
    VALUES
    (
        p_i_chi_nhanh_id,
        trim(p_str_ma_dich_vu),
        trim(p_str_ten_dich_vu),
        p_str_mo_ta,
        p_dec_don_gia,
        p_i_loai_phi_id,
        p_str_last_updated_by,
        p_str_last_updated_by,
        p_str_last_updated_by_function,
        p_str_last_updated_by_function
    )
    RETURNING auto_id INTO v_i_auto_id;

    RETURN v_i_auto_id;
END;
$$;

CREATE OR REPLACE FUNCTION fq_201_dvht_sp_upd_update(
    p_i_auto_id bigint,
    p_i_chi_nhanh_id bigint,
    p_str_ma_dich_vu varchar,
    p_str_ten_dich_vu varchar,
    p_str_mo_ta varchar,
    p_dec_don_gia numeric,
    p_i_loai_phi_id integer,
    p_i_is_hoat_dong integer,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_dich_vu_ho_tro
    SET chi_nhanh_id = p_i_chi_nhanh_id,
        ma_dich_vu = trim(p_str_ma_dich_vu),
        ten_dich_vu = trim(p_str_ten_dich_vu),
        mo_ta = p_str_mo_ta,
        don_gia = p_dec_don_gia,
        loai_phi_id = p_i_loai_phi_id,
        is_hoat_dong = p_i_is_hoat_dong,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE FUNCTION fq_201_dvht_sp_del_delete_by_id(
    p_i_auto_id bigint,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_dich_vu_ho_tro
    SET deleted = 1,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE FUNCTION fq_202_bgi_sp_sel_list_by_created(p_dtm_from timestamptz, p_dtm_to timestamptz)
RETURNS SETOF view_dm_bang_gia_in
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.kho_giay_id,
        a.kieu_in_id,
        a.mau_in_id,
        a.is_photo,
        a.don_gia,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_bang_gia_in a
    WHERE a.created >= p_dtm_from
        AND a.created <= p_dtm_to
    ORDER BY a.created DESC;
$$;

CREATE OR REPLACE FUNCTION fq_202_bgi_sp_sel_get_by_id(p_i_auto_id bigint)
RETURNS view_dm_bang_gia_in
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id,
        a.chi_nhanh_id,
        a.kho_giay_id,
        a.kieu_in_id,
        a.mau_in_id,
        a.is_photo,
        a.don_gia,
        a.is_hoat_dong,
        a.legacy_uuid,
        a.deleted,
        a.created,
        a.created_by,
        a.last_updated,
        a.last_updated_by,
        a.created_by_function,
        a.last_updated_by_function
    FROM view_dm_bang_gia_in a
    WHERE a.auto_id = p_i_auto_id;
$$;

CREATE OR REPLACE FUNCTION fq_202_bgi_sp_ins_insert(
    p_i_chi_nhanh_id bigint,
    p_i_kho_giay_id bigint,
    p_i_kieu_in_id bigint,
    p_i_mau_in_id bigint,
    p_i_is_photo integer,
    p_dec_don_gia numeric,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_i_auto_id bigint;
BEGIN
    INSERT INTO tbl_dm_bang_gia_in
    (
        chi_nhanh_id,
        kho_giay_id,
        kieu_in_id,
        mau_in_id,
        is_photo,
        don_gia,
        created_by,
        last_updated_by,
        created_by_function,
        last_updated_by_function
    )
    VALUES
    (
        p_i_chi_nhanh_id,
        p_i_kho_giay_id,
        p_i_kieu_in_id,
        p_i_mau_in_id,
        p_i_is_photo,
        p_dec_don_gia,
        p_str_last_updated_by,
        p_str_last_updated_by,
        p_str_last_updated_by_function,
        p_str_last_updated_by_function
    )
    RETURNING auto_id INTO v_i_auto_id;

    RETURN v_i_auto_id;
END;
$$;

CREATE OR REPLACE FUNCTION fq_202_bgi_sp_upd_update(
    p_i_auto_id bigint,
    p_i_chi_nhanh_id bigint,
    p_i_kho_giay_id bigint,
    p_i_kieu_in_id bigint,
    p_i_mau_in_id bigint,
    p_i_is_photo integer,
    p_dec_don_gia numeric,
    p_i_is_hoat_dong integer,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_bang_gia_in
    SET chi_nhanh_id = p_i_chi_nhanh_id,
        kho_giay_id = p_i_kho_giay_id,
        kieu_in_id = p_i_kieu_in_id,
        mau_in_id = p_i_mau_in_id,
        is_photo = p_i_is_photo,
        don_gia = p_dec_don_gia,
        is_hoat_dong = p_i_is_hoat_dong,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE FUNCTION fq_202_bgi_sp_del_delete_by_id(
    p_i_auto_id bigint,
    p_str_last_updated_by varchar,
    p_str_last_updated_by_function varchar
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE tbl_dm_bang_gia_in
    SET deleted = 1,
        last_updated_by = p_str_last_updated_by,
        last_updated_by_function = p_str_last_updated_by_function
    WHERE auto_id = p_i_auto_id
        AND deleted = 0;
END;
$$;

CREATE OR REPLACE FUNCTION f2004_sp_sel_reconcile_ton_kho_san_pham()
RETURNS TABLE
(
    ton_kho_san_pham_id bigint,
    chi_nhanh_id bigint,
    san_pham_id bigint,
    so_luong_ton integer,
    so_luong_theo_nhap_xuat integer,
    chenh_lech integer
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        a.auto_id AS ton_kho_san_pham_id,
        a.chi_nhanh_id,
        a.san_pham_id,
        a.so_luong_ton,
        COALESCE(SUM(b.so_luong_thay_doi), 0)::integer AS so_luong_theo_nhap_xuat,
        (a.so_luong_ton - COALESCE(SUM(b.so_luong_thay_doi), 0))::integer AS chenh_lech
    FROM tbl_xnk_ton_kho_san_pham a
    LEFT JOIN tbl_xnk_nhap_xuat_san_pham b
        ON b.ton_kho_san_pham_id = a.auto_id
        AND b.deleted = 0
    WHERE a.deleted = 0
    GROUP BY
        a.auto_id,
        a.chi_nhanh_id,
        a.san_pham_id,
        a.so_luong_ton;
$$;

CREATE OR REPLACE FUNCTION fq_sys_sp_sel_duplicate_idempotency_key()
RETURNS TABLE
(
    ten_bang varchar,
    idempotency_key varchar,
    chi_nhanh_id bigint,
    thanh_vien_id bigint,
    so_luong bigint
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        'tbl_tc_giao_dich_vi'::varchar AS ten_bang,
        lower(a.idempotency_key)::varchar AS idempotency_key,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        count(*) AS so_luong
    FROM tbl_tc_giao_dich_vi a
    WHERE a.deleted = 0
        AND a.idempotency_key IS NOT NULL
    GROUP BY
        lower(a.idempotency_key),
        a.chi_nhanh_id,
        a.thanh_vien_id
    HAVING count(*) > 1
    UNION ALL
    SELECT
        'tbl_tc_yeu_cau_nap_tien'::varchar,
        lower(a.create_idempotency_key)::varchar,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        count(*)
    FROM tbl_tc_yeu_cau_nap_tien a
    WHERE a.deleted = 0
        AND a.create_idempotency_key IS NOT NULL
    GROUP BY
        lower(a.create_idempotency_key),
        a.chi_nhanh_id,
        a.thanh_vien_id
    HAVING count(*) > 1
    UNION ALL
    SELECT
        'tbl_tc_don_in'::varchar,
        lower(a.submit_idempotency_key)::varchar,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        count(*)
    FROM tbl_tc_don_in a
    WHERE a.deleted = 0
        AND a.submit_idempotency_key IS NOT NULL
    GROUP BY
        lower(a.submit_idempotency_key),
        a.chi_nhanh_id,
        a.thanh_vien_id
    HAVING count(*) > 1
    UNION ALL
    SELECT
        'tbl_tc_don_hang_san_pham'::varchar,
        lower(a.order_idempotency_key)::varchar,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        count(*)
    FROM tbl_tc_don_hang_san_pham a
    WHERE a.deleted = 0
        AND a.order_idempotency_key IS NOT NULL
    GROUP BY
        lower(a.order_idempotency_key),
        a.chi_nhanh_id,
        a.thanh_vien_id
    HAVING count(*) > 1
    UNION ALL
    SELECT
        'tbl_tc_don_dich_vu_ho_tro'::varchar,
        lower(a.order_idempotency_key)::varchar,
        a.chi_nhanh_id,
        a.thanh_vien_id,
        count(*)
    FROM tbl_tc_don_dich_vu_ho_tro a
    WHERE a.deleted = 0
        AND a.order_idempotency_key IS NOT NULL
    GROUP BY
        lower(a.order_idempotency_key),
        a.chi_nhanh_id,
        a.thanh_vien_id
    HAVING count(*) > 1;
$$;

CREATE OR REPLACE FUNCTION fq_sys_sp_sel_cross_branch_violation()
RETURNS TABLE
(
    ma_loi varchar,
    ten_bang varchar,
    ref_id bigint,
    chi_nhanh_id bigint,
    chi_nhanh_lien_quan_id bigint,
    mo_ta varchar
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        'DON_IN_FILE'::varchar AS ma_loi,
        'tbl_tc_don_in'::varchar AS ten_bang,
        a.auto_id AS ref_id,
        a.chi_nhanh_id,
        b.chi_nhanh_id AS chi_nhanh_lien_quan_id,
        'Don in va file upload khac chi nhanh.'::varchar AS mo_ta
    FROM tbl_tc_don_in a
    JOIN tbl_tc_file_upload b
        ON b.auto_id = a.file_upload_id
        AND b.deleted = 0
    WHERE a.deleted = 0
        AND a.chi_nhanh_id <> b.chi_nhanh_id
    UNION ALL
    SELECT
        'DON_HANG_SAN_PHAM'::varchar,
        'tbl_tc_don_hang_san_pham_chi_tiet'::varchar,
        a.auto_id,
        b.chi_nhanh_id,
        c.chi_nhanh_id,
        'Don hang san pham va san pham khac chi nhanh.'::varchar
    FROM tbl_tc_don_hang_san_pham_chi_tiet a
    JOIN tbl_tc_don_hang_san_pham b
        ON b.auto_id = a.don_hang_san_pham_id
        AND b.deleted = 0
    JOIN tbl_dm_san_pham c
        ON c.auto_id = a.san_pham_id
        AND c.deleted = 0
    WHERE a.deleted = 0
        AND b.chi_nhanh_id <> c.chi_nhanh_id
    UNION ALL
    SELECT
        'DON_DICH_VU_HO_TRO'::varchar,
        'tbl_tc_don_dich_vu_ho_tro'::varchar,
        a.auto_id,
        a.chi_nhanh_id,
        b.chi_nhanh_id,
        'Don dich vu va dich vu ho tro khac chi nhanh.'::varchar
    FROM tbl_tc_don_dich_vu_ho_tro a
    JOIN tbl_dm_dich_vu_ho_tro b
        ON b.auto_id = a.dich_vu_ho_tro_id
        AND b.deleted = 0
    WHERE a.deleted = 0
        AND a.chi_nhanh_id <> b.chi_nhanh_id
    UNION ALL
    SELECT
        'VI_GIAO_DICH'::varchar,
        'tbl_tc_giao_dich_vi'::varchar,
        a.auto_id,
        a.chi_nhanh_id,
        b.chi_nhanh_id,
        'Giao dich vi va vi chi nhanh khac chi nhanh.'::varchar
    FROM tbl_tc_giao_dich_vi a
    JOIN tbl_tc_vi_chi_nhanh b
        ON b.auto_id = a.vi_chi_nhanh_id
        AND b.deleted = 0
    WHERE a.deleted = 0
        AND a.chi_nhanh_id <> b.chi_nhanh_id;
$$;

INSERT INTO tbl_sys_database_version
(
    patch_id,
    description,
    created_by_function,
    last_updated_by_function
)
VALUES
(
    'V20260704_001_tks_canonical_webphotocopyhub',
    'Create TKS canonical PostgreSQL schema, views, tracking triggers, seed enums, and core routines.',
    'V20260704_001',
    'V20260704_001'
)
ON CONFLICT (patch_id) DO UPDATE
SET description = EXCLUDED.description,
    last_updated_by_function = EXCLUDED.last_updated_by_function;

COMMIT;
