<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PhotoCopyHub.Web.Admin</RootNamespace>
    <AssemblyName>PhotoCopyHub.Web.Admin</AssemblyName>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebPhotocopyHub_Data_Access\Domain\PhotoCopyHub.Domain.csproj" />
    <ProjectReference Include="..\WebPhotocopyHub_Data_Access\Application\PhotoCopyHub.Application.csproj" />
    <ProjectReference Include="..\WebPhotocopyHub_Report\WebPhotocopyHub_Report.csproj" />
    <ProjectReference Include="..\WebPhotocopyHub_Web_Common\WebPhotocopyHub_Web_Common.csproj" />
  </ItemGroup>

</Project>
