<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PhotoCopyHub.DataAccess</RootNamespace>
    <AssemblyName>PhotoCopyHub.DataAccess</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Sql\**\*.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Application\**" />
    <Compile Remove="Domain\**" />
    <Compile Remove="Entities\**" />
    <Compile Remove="Infrastructure\**" />
    <EmbeddedResource Remove="Application\**" />
    <EmbeddedResource Remove="Domain\**" />
    <EmbeddedResource Remove="Entities\**" />
    <EmbeddedResource Remove="Infrastructure\**" />
    <None Remove="Application\**" />
    <None Remove="Domain\**" />
    <None Remove="Entities\**" />
    <None Remove="Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Domain\PhotoCopyHub.Domain.csproj" />
    <ProjectReference Include="Application\PhotoCopyHub.Application.csproj" />
    <ProjectReference Include="Infrastructure\PhotoCopyHub.Infrastructure.csproj" />
  </ItemGroup>

</Project>
