<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WebPhotocopyHub.Web.Shop</RootNamespace>
    <AssemblyName>WebPhotocopyHub.Web.Shop</AssemblyName>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebPhotocopyHub.Domain\WebPhotocopyHub.Domain.csproj" />
    <ProjectReference Include="..\WebPhotocopyHub.Application\WebPhotocopyHub.Application.csproj" />
  </ItemGroup>
</Project>